apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: sourcegraph-ingress
  annotations:
    kubernetes.io/ingress.class: traefik
spec:
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: sourcegraph-frontend
                port:
                  number: 30080
