steps:
  - label: ":bazel: Build"
    agents:
      queue: bazel
    commands: |
      export AWS_ACCESS_KEY_ID=$$RELEASE_AWS_ACCESS_KEY
      export AWS_SECRET_ACCESS_KEY=$$RELEASE_AWS_SECRET_KEY
      bazel run //:packer -- init --var-file=./packer/build-variables.hcl ./packer/aws/aws-builder.pkr.hcl
      # RELEASE_NUMBER comes from `github.ref_name` in the GHA that triggers this
      # Tag names now include a "v", which we remove here
      bazel run //:packer -- build -var "instance_version=$$(echo $RELEASE_NUMBER | tr -d v)" -var "dev=false" --var-file=./packer/build-variables.hcl ./packer/aws/aws-builder.pkr.hcl
      bazel run //:generate-changelog
      ./volume_cleanup.sh
      git checkout -b "release/$RELEASE_NUMBER"
      git add CHANGELOG.md
      git commit -m "Update Changelog"
      git push --set-upstream origin "release/$RELEASE_NUMBER"
      gh pr create --fill \
        --title "Changelog Hashes for $RELEASE_NUMBER" \
        --body "Automated publish"
    artifact_paths:
      - "CHANGELOG.md"
